#ifndef CONFIG_HPP
#define CONFIG_HPP


// Default configurations
#define DEFAULT_PATTERN_PATH "target.pat"
#define DEFAULT_SUBPOP_COUNT "8"
#define DEFAULT_TOTAL_GENERATIONS "262144"
#define DEFAULT_GENERATIONS_PER_CYCLE "1024"
#define DEFAULT_SUBPOP_SIZE "4"
#define DEFAULT_GENOME_SIZE "1024"



#endif // CONFIG_HPP
